config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs
  get '/top' => 'home#index'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	attachment :image

 def self.search(search)
    if search
      Blog.where(Blog.arel_table[:title].matches("%#{search}%")) 
    else
      Blog.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


  def index
  	@blog = Blog.new
    @blogs = Blog.search(params[:search])

  end

  def show
      @blog = Blog.find(params[:id])
  end

  def new
  	 @blog = Blog.new
  end

  def create
  	  blog = Blog.new(blog_params)
  	  blog.save
  	  redirect_to blog_path(blog.id)
  end

  def edit
  	@blog = Blog.find(params[:id])
  end

  def update
  	blog = Blog.find(params[:id])
  	blog.update(blog_params)
  	redirect_to blog_path(blog.id)
  end

  def destroy
  	blog = Blog.find(params[:id])
  	blog.destroy
  	redirect_to blogs_path
  end

  private
  def blog_params
  	params.require(:blog).permit(:title, :opinion, :image)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/edit.html.erb
<div class="container">

<h1>edit blog</h1>


<%= form_for(@blog) do |f| %>
		<div class="form-group">

			<label>title</label>
		<%= f.text_field :title, class: "form-control" %>


		<br>


		    <label>opinion</label>
		<%= f.text_field :opinion, class: "form-control" %>

		<br>

		    <label>image</label>

		<%= f.attachment_field :image %>

		<br>
	    </div>


		<%= f.submit 'update book', class: "square_btn" %>

<% end %> <br>


		<%= link_to 'show', blog_path, class: "btn btn-primary" %>

		|

		<%= link_to 'back', :back, class: "btn btn-info" %>

app/views/blogs/index.html.erb
<div class="container">


　　　<div class="row">


	<div class="col-xs-6 col-lg-6">


<h2>new book</h2>

<%= bootstrap_form_for(@blog) do |f| %>

	<%= f.text_field :title %>

	<%= f.text_field :opinion %>

	<%= f.attachment_field :image %>

<br>

	<%= f.submit 'create', class: "square_btn" %>

<% end %>

</div>

	　　　<div class="col-xs-6 col-lg-6">

 <table class="table table-striped">

 	<thead>
 		<tr>
 			<th>title</th>
 			<th>opinion</th>
 			<th>image</th>
 		</tr>
 	</thead>
 	<tbody>
 		<% @blogs.each do |blog| %>
 		<tr>
 			<td>
 				<%= blog.title %>
 			</td>
 			<td>
 				<%= blog.opinion %>
 			</td>
 			<td>
 				<%= attachment_image_tag blog, :image, :fill, 30, 30, format: 'jpeg' %>
 		    </td>
 		    <td>
 			    <%= link_to "show", blog_path(blog.id), class: "btn btn-primary" %>
 			</td>
 			<td>
 			    <%= link_to "edit", edit_blog_path(blog.id), class: "btn btn-info" %>
 			</td>
 			<td>
 			    <%= link_to "destroy", blog_path(blog.id), method: :delete, class: "btn btn-danger" %>
 			</td>

 		    </td>
 	    </tr>
 	</tbody>
 <% end %>
 </table>


</div>


<footer>

	<h3></h3>

</footer>

</div>

</div>

app/views/blogs/show.html.erb
<div class="container">


 <table class="table table-striped">

 	<thead>
 		<tr>
 			<th>title</th>
 			<th>opinion</th>
 			<th>image</th>
 		</tr>
 	</thead>
 	<tbody>
 		
 		<tr>
 			<td>
 				<%= @blog.title %>
 			</td>
 			<td>
 				<%= @blog.opinion %>
 			</td>
 			<td>
 				<%= attachment_image_tag @blog, :image, :fill, 100, 100, format: 'jpeg' %>
 		    </td>
 		    <td>
 		    	<%= link_to 'edit', edit_blog_path, class: "btn btn-primary" %>
 		    </td>
 		    <td>

 			    <%= link_to 'back', :back, class: "btn btn-info" %>

 		    </td>
 	    </tr>
 	</tbody>
 </table>

app/views/home/index.html.erb
<div class="container">

<h1>ようこそブログくんへ</h1>
<p>ただのブログサービスです。</p>


<%= link_to "start", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogkun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<head>

   <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="#">blogs</a>




          <%= form_tag blogs_path,method: "get" do %>
          <div class="input-group mado">

          <input name="search" class="form-control">

          <span class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class='glyphicon glyphicon-search'></i>
          </button>

          </span>
          </div>

          <% end %>

        </div>
      </div>
    </nav>
 </body>


  </div>

</head>




    <%= yield %>

  </body>

</html>